version: '3'

services:
  app:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./application:/application
    command: >
      sh -c "python3 manage.py migrate &&
             python3 manage.py wait_for_db &&
             python3 manage.py runserver 0.0.0.0:8000"

    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data
  redis:
    image: redis
  celery:
    restart: always
    build:
      context: .
    command: celery -A application worker -l info
    volumes:
      - ./application:/application
    env_file:
      - .env
    depends_on:
      - db
      - redis
      - app
volumes:
  pgdata: